server:
  port: 9088
  route-prefix: /api
  node-id: 1

jwt:
  secret: linyu_cL8$yF6^yA
  expire-hours: 24

email:
  host: smtp.163.com
  port: 465
  form-addr: linyuteam@163.com
  password: 123456
  username: 林语团队

livekit:
  host: 127.0.0.1:7880
  key: devkey
  secret: devsecret

cache:
  type: redis
  redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
  otter:
    capacity: 10000

rdb:
  type: mysql
  mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: linyu
    timezone: Asia/Shanghai
  sqlite:
    db-path: ./linyu/db
    db-name: linyu

storage:
  type: oss
  local:
    base-url: http://localhost:9088
    file-path: ./linyu/storage
  oss:
    base-url: https://xxxx.com
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: access-key-id
    access-key-secret: access-key-secret
    bucket-name: linyu


event-bus:
  #"local" 或 "rocket"
  type: local
  rocket:
    namesrv:
      - 192.168.166.105:9876
    retry-times: 2

auth:
  ldap:
    enabled: true
    host: ldap://127.0.0.1:389
    bind-dn: cn=admin,dc=example,dc=com
    bind-password: admin
    base-dn: dc=example,dc=com
    #ldap查询条件（用于登录名称和密码校验）
    user-filter: (cn=%s)

    #ldap和本地库唯一映射关系
    unique:
      ldap-field: "mobile" #ldap对应的字段key
      local-field: "phone" #本地库对应的字段key（phone,email,id,account）